## (1) Load Processed Data in the Paper

Currently, we support norman / adamson / dixit.

In [1]:
import sys
sys.path.append('../')

from gears import PertData

pert_data = PertData('./data') # specific saved folder
pert_data.load(data_name = 'norman') # specific dataset name
pert_data.prepare_split(split = 'simulation', seed = 1) # get data split with seed
pert_data.get_dataloader(batch_size = 32, test_batch_size = 128) # prepare data loader

Downloading...
100%|█████████████████████████████████████| 9.46M/9.46M [00:01<00:00, 8.04MiB/s]
Downloading...
100%|███████████████████████████████████████| 559k/559k [00:00<00:00, 1.54MiB/s]
Downloading...
100%|███████████████████████████████████████| 169M/169M [00:35<00:00, 4.75MiB/s]
Extracting zip file...
Done!
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['RHOXF2BB+ctrl' 'LYL1+IER5L' 'ctrl+IER5L' 'KIAA1804+ctrl' 'IER5L+ctrl'
 'RHOXF2BB+ZBTB25' 'RHOXF2BB+SET']
Creating pyg object for each cell in the data...
100%|█████████████████████████████████████████| 277/277 [04:15<00:00,  1.08it/s]
Saving new dataset pyg object at ./data/norman/data_pyg/cell_graphs.pkl
Done!
Creating new splits....
Saving new splits at ./data/norman/splits/norman_simulation_1_0.75.pkl
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!

## (2) Create your own Perturb-Seq data
Prepare a scanpy adata object with 
1. `adata.obs` dataframe has `condition` and `cell_type` columns, where `condition` is the perturbation name for each cell. Control cells have condition format of `ctrl`, single perturbation has condition format of `A+ctrl` or `ctrl+A`, combination perturbation has condition format of `A+B`.
2. `adata.var` dataframe has `gene_name` column, where each gene name is the gene symbol.
3. `adata.X` stores the post-perturbed gene expression. 

Here an example using dixit 2016 dataset.

In [2]:
import scanpy as sc
adata = sc.read_h5ad('./data/crispri_fitness.h5ad')
adata

AnnData object with n_obs × n_vars = 31202 × 36518
    obs: 'condition', 'cell_type', 'batch', 'guide_call', 'n_genes'
    var: 'gene_name', 'n_cells'

In [3]:
adata.var.head(2)

,gene_name,n_cells
Unnamed: 0,,
ENSG00000243485:MIR1302-2HG:Gene-Expression,ENSG00000243485:MIR1302-2HG:Gene-Expression,53
ENSG00000237613:FAM138A:Gene-Expression,ENSG00000237613:FAM138A:Gene-Expression,0

In [4]:
adata.obs.head(2)

                        condition cell_type
TAACATGAAAAGTG_p7d_F3  CREB1+ctrl      K562
CTATCCCTTGTGCA_p7d_G3  GABPA+ctrl      K562

In [4]:
adata.obs.head(2)

,condition,cell_type,batch,guide_call,n_genes
MP-ST-P3-D3_I1_AAACCTGCAGCTCGCA-1,ctrl,wahn_1,GenomeWideScreen_FitnessGenes_Pool3_Day3_Inlet1,unassigned,6456
MP-ST-P3-D3_I1_AAACCTGGTACGCTGC-1,GIGYF2+ctrl,wahn_1,GenomeWideScreen_FitnessGenes_Pool3_Day3_Inlet1,GIGYF2_ACGGAACGGCTGGTTACCTG,4659

### Suggested normalization

For raw count data we recommend the following normalization and subsetting to the top 5000 most variable genes

In [5]:
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
sc.pp.highly_variable_genes(adata,n_top_genes=5000, subset=True)

### Create dataloader

GEARS will take it from here. The new data processing takes around 15 minutes for 5K genes and 100K cells.

In [5]:
import sys
sys.path.append('../')

from gears import PertData

pert_data = PertData('./data') # specific saved folder
pert_data.new_data_process(dataset_name = 'wahn_1', adata = adata) # specific dataset name and adata object
pert_data.load(data_path = './data/wahn_1') # load the processed data, the path is saved folder + dataset_name
pert_data.prepare_split(split = 'simulation', seed = 1) # get data split with seed
pert_data.get_dataloader(batch_size = 32, test_batch_size = 128) # prepare data loader

Trying to set attribute `.obs` of view, copying.
... storing 'dose_val' as categorical
Trying to set attribute `.obs` of view, copying.
... storing 'condition_name' as categorical
... storing 'dose_val' as categorical
... storing 'condition_name' as categorical
Creating pyg object for each cell in the data...
100%|█████████████████████████████████████████████████████████████████████████| 20/20 [00:51<00:00,  2.56s/it]
Saving new dataset pyg object at ./data/dixit/data_pyg/cell_graphs.pkl
Done!
Local copy of pyg dataset is detected. Loading...
Done!
Creating new splits....
Saving new splits at ./data/dixit/splits/dixit_simulation_1_0.75.pkl
Simulation split test composition:
combo_seen0:0
combo_seen1:0
combo_seen2:0
unseen_single:5
Done!
Creating dataloaders....
Done!

In [6]:
import sys
sys.path.append('../')

from gears import PertData

pert_data = PertData('./data') # specific saved folder
pert_data.new_data_process(dataset_name = 'wahn_1', adata = adata) # specific dataset name and adata object
pert_data.load(data_path = './data/wahn_1') # load the processed data, the path is saved folder + dataset_name
pert_data.prepare_split(split = 'simulation', seed = 1) # get data split with seed
pert_data.get_dataloader(batch_size = 32, test_batch_size = 128) # prepare data loader

Found local copy...
Found local copy...
Creating pyg object for each cell in the data...
Creating dataset file...
  0%|          | 1/1265 [00:02<47:12,  2.24s/it]

LETM2+ctrl

  1%|          | 13/1265 [00:02<02:19,  9.00it/s]

PRR23A+ctrl
GOLGA6C+ctrl
NLRP3+ctrl
CCNYL1+ctrl

  3%|▎         | 35/1265 [00:03<00:38, 31.68it/s]

TMEM144+ctrl
SLITRK5+ctrl

  4%|▎         | 47/1265 [00:03<00:30, 40.35it/s]

ZACN+ctrl
CRACR2B+ctrl
FAM89A+ctrl

  5%|▌         | 66/1265 [00:03<00:24, 48.10it/s]

ICE2+ctrl

 11%|█▏        | 143/1265 [00:04<00:16, 66.48it/s]

PLD2+ctrl
ST8SIA6+ctrl
C10orf111+ctrl

 12%|█▏        | 150/1265 [00:05<00:17, 64.19it/s]

FANCC+ctrl
GRAMD2+ctrl

 14%|█▎        | 171/1265 [00:05<00:18, 58.78it/s]

U2AF1L5+ctrl

 14%|█▍        | 183/1265 [00:05<00:20, 53.84it/s]

LRRK1+ctrl
WRB+ctrl

 16%|█▌        | 197/1265 [00:05<00:18, 57.66it/s]

CELF5+ctrl
NEFL+ctrl
CLDN11+ctrl
ELOC+ctrl

 17%|█▋        | 221/1265 [00:06<00:15, 68.74it/s]

HDGFRP3+ctrl
GPR12+ctrl

 20%|█▉        | 249/1265 [00:06<00:15, 64.77it/s]

NTSR2+ctrl
SKIV2L2+ctrl
PLEK2+ctrl
DGCR14+ctrl

 21%|██        | 263/1265 [00:06<00:16, 59.54it/s]

CX3CL1+ctrl
NUPL2+ctrl

 22%|██▏       | 278/1265 [00:07<00:16, 59.00it/s]

GNMT+ctrl
KLHL14+ctrl
TANC1+ctrl
SLC17A7+ctrl

 23%|██▎       | 297/1265 [00:07<00:17, 56.57it/s]

AKAP10+ctrl
LARGE2+ctrl
MYL2+ctrl

 25%|██▍       | 312/1265 [00:07<00:15, 63.26it/s]

NARFL+ctrl
SAP25+ctrl
FAM173B+ctrl

 26%|██▌       | 328/1265 [00:08<00:16, 58.19it/s]

CCDC121+ctrl
RBSN+ctrl
TEX14+ctrl

 27%|██▋       | 347/1265 [00:08<00:16, 56.03it/s]

TSACC+ctrl
FAM189A1+ctrl

 29%|██▉       | 368/1265 [00:08<00:14, 62.51it/s]

CPTP+ctrl
CTC1+ctrl

 32%|███▏      | 401/1265 [00:09<00:11, 73.97it/s]

OPRK1+ctrl
PPL+ctrl

 33%|███▎      | 416/1265 [00:09<00:13, 64.04it/s]

NKAIN1+ctrl

 34%|███▍      | 430/1265 [00:09<00:14, 59.22it/s]

ATP5O+ctrl
UTP14C+ctrl

 35%|███▌      | 444/1265 [00:09<00:13, 58.66it/s]

SLC6A3+ctrl
SWAP70+ctrl
CFAP20+ctrl
SLC22A5+ctrl

 36%|███▌      | 458/1265 [00:10<00:13, 57.80it/s]

TMEM229B+ctrl
C19orf71+ctrl
GNA12+ctrl
HLA+ctrl

 37%|███▋      | 472/1265 [00:10<00:12, 61.37it/s]

SF3B6+ctrl
C16orf90+ctrl
DNAH17+ctrl

 39%|███▊      | 488/1265 [00:10<00:11, 65.43it/s]

CCL21+ctrl
C18orf21+ctrl
SNTG2+ctrl
PNMAL2+ctrl

 40%|████      | 510/1265 [00:10<00:11, 64.55it/s]

CNGA1+ctrl
C9orf152+ctrl
SDPR+ctrl
TMC5+ctrl
C7orf26+ctrl
FRMD5+ctrl

 42%|████▏     | 528/1265 [00:11<00:10, 71.18it/s]

SLC6A20+ctrl
C21orf59+ctrl

 43%|████▎     | 544/1265 [00:11<00:10, 68.70it/s]

TNFRSF25+ctrl
LRRC10B+ctrl
KCNJ12+ctrl
ATP5L+ctrl

 45%|████▌     | 575/1265 [00:11<00:09, 73.77it/s]

CDH23+ctrl
ABCA2+ctrl
CHRDL2+ctrl
ATP5D+ctrl
CCR6+ctrl

 47%|████▋     | 591/1265 [00:12<00:09, 67.58it/s]

C15orf52+ctrl
PGAP1+ctrl
KCNH8+ctrl

 48%|████▊     | 608/1265 [00:12<00:09, 72.52it/s]

C1orf21+ctrl
CCDC166+ctrl

 49%|████▉     | 625/1265 [00:12<00:08, 78.29it/s]

CRISPLD1+ctrl

 51%|█████     | 643/1265 [00:12<00:07, 78.84it/s]

VAT1L+ctrl
SMN1+ctrl
USMG5+ctrl

 52%|█████▏    | 661/1265 [00:13<00:07, 77.04it/s]

PARP3+ctrl
SEM1+ctrl
GOLGA7B+ctrl
LCN6+ctrl

 54%|█████▎    | 677/1265 [00:13<00:08, 70.86it/s]

TOMM20L+ctrl
HASPIN+ctrl
C22orf46+ctrl
ST8SIA4+ctrl
RAD9B+ctrl

 54%|█████▍    | 685/1265 [00:13<00:08, 71.34it/s]

MED14OS+ctrl
SULT4A1+ctrl
ATG101+ctrl

 56%|█████▌    | 710/1265 [00:13<00:07, 75.69it/s]

MRPL57+ctrl

 58%|█████▊    | 728/1265 [00:13<00:06, 80.26it/s]

SPATA7+ctrl
ALDH6A1+ctrl

 60%|█████▉    | 755/1265 [00:14<00:06, 74.93it/s]

PRSS38+ctrl
MS4A12+ctrl

 62%|██████▏   | 783/1265 [00:14<00:06, 76.41it/s]

ADAMTS15+ctrl
COLEC12+ctrl
FAM96B+ctrl

 64%|██████▍   | 807/1265 [00:14<00:06, 71.63it/s]

C14orf166+ctrl
SOCS6+ctrl

 65%|██████▌   | 825/1265 [00:15<00:05, 77.48it/s]

RGS13+ctrl
KLHL26+ctrl
KDM4D+ctrl

 67%|██████▋   | 843/1265 [00:15<00:05, 80.08it/s]

BAALC+ctrl
SPOCK1+ctrl
ATP5J2+ctrl
OTUD7A+ctrl
C8orf59+ctrl

 69%|██████▉   | 871/1265 [00:15<00:04, 84.39it/s]

KIAA0556+ctrl
MUM1+ctrl
TMTC2+ctrl
ABCC9+ctrl
C16orf59+ctrl

 70%|███████   | 890/1265 [00:15<00:04, 84.44it/s]

BTBD6+ctrl
FAM92B+ctrl
TNFRSF13C+ctrl
SORCS2+ctrl
HABP4+ctrl
PGM5+ctrl

 71%|███████   | 900/1265 [00:16<00:04, 88.18it/s]

CALCR+ctrl
NARR+ctrl

 74%|███████▍  | 939/1265 [00:16<00:03, 88.11it/s]

ADAMTS8+ctrl
SCGB1C2+ctrl
CACNG7+ctrl
HPSE+ctrl
LOC101927322+ctrl

 77%|███████▋  | 968/1265 [00:16<00:03, 89.99it/s]

TRIM16L+ctrl
TKFC+ctrl
CRIP1+ctrl

 79%|███████▉  | 998/1265 [00:17<00:02, 91.13it/s]

GRAMD2A+ctrl
FAXC+ctrl

 80%|████████  | 1018/1265 [00:17<00:02, 90.57it/s]

GGT7+ctrl
MTERF3+ctrl

 82%|████████▏ | 1039/1265 [00:17<00:02, 95.11it/s]

IKBKAP+ctrl
SLC16A3+ctrl

 83%|████████▎ | 1049/1265 [00:17<00:02, 95.19it/s]

PTGDS+ctrl

 85%|████████▍ | 1070/1265 [00:18<00:03, 55.52it/s]

FAM163A+ctrl
MOSPD2+ctrl
RASL10A+ctrl

 86%|████████▌ | 1089/1265 [00:18<00:02, 67.85it/s]

NGB+ctrl

 89%|████████▉ | 1132/1265 [00:18<00:01, 92.86it/s]

KIAA1429+ctrl

 91%|█████████ | 1152/1265 [00:19<00:01, 89.61it/s]

ABCD1+ctrl
GNB1L+ctrl
C17orf64+ctrl

 94%|█████████▎| 1184/1265 [00:19<00:00, 98.58it/s]

ORAOV1+ctrl
UBOX5+ctrl
BOD1L2+ctrl
CLIP4+ctrl

 95%|█████████▌| 1207/1265 [00:19<00:00, 105.14it/s]

C1orf226+ctrl
SERF1A+ctrl

 97%|█████████▋| 1232/1265 [00:19<00:00, 110.60it/s]

RASEF+ctrl
LOC389895+ctrl
RIMKLA+ctrl

100%|██████████| 1265/1265 [00:20<00:00, 62.68it/s]
Done!
Saving new dataset pyg object at ./data\wahn_1\data_pyg\cell_graphs.pkl

DZANK1+ctrl
SPSB4+ctrl
SOBP+ctrl
WNT7B+ctrl
SLX4+ctrl
VSTM5+ctrl
CBWD7+ctrl
NT5DC4+ctrl

Done!
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
177
['LETM2+ctrl' 'PRR23A+ctrl' 'GOLGA6C+ctrl' 'NLRP3+ctrl' 'CCNYL1+ctrl'
 'TMEM144+ctrl' 'SLITRK5+ctrl' 'ZACN+ctrl' 'CRACR2B+ctrl' 'FAM89A+ctrl'
 'ICE2+ctrl' 'PLD2+ctrl' 'ST8SIA6+ctrl' 'C10orf111+ctrl' 'FANCC+ctrl'
 'GRAMD2+ctrl' 'U2AF1L5+ctrl' 'LRRK1+ctrl' 'WRB+ctrl' 'CELF5+ctrl'
 'NEFL+ctrl' 'CLDN11+ctrl' 'ELOC+ctrl' 'HDGFRP3+ctrl' 'GPR12+ctrl'
 'NTSR2+ctrl' 'SKIV2L2+ctrl' 'PLEK2+ctrl' 'DGCR14+ctrl' 'CX3CL1+ctrl'
 'NUPL2+ctrl' 'GNMT+ctrl' 'KLHL14+ctrl' 'TANC1+ctrl' 'SLC17A7+ctrl'
 'AKAP10+ctrl' 'LARGE2+ctrl' 'MYL2+ctrl' 'NARFL+ctrl' 'SAP25+ctrl'
 'FAM173B+ctrl' 'CCDC121+ctrl' 'RBSN+ctrl' 'TEX14+ctrl' 'TSACC+ctrl'
 'FAM189A1+ctrl' 'CPTP+ctrl' 'CTC1+ctrl' 'OPRK1+ctrl' 'PPL+ctrl'
 'NKAIN1+ctrl' 'ATP5O+ctrl' 'UTP14C+ctrl' 'SLC6A3+ctrl' 'SWAP70+ctrl'
 'CFAP20+ctrl' 'SLC22A5+ctrl' 'TMEM229B+ctrl' 'C19orf71+ctrl' 'GNA12+ctrl'
 'HLA+ctrl' 'SF3B6+ctrl' 'C16orf90+ctrl' 'DNAH17+ctrl' 'CCL21+ctrl'
 'C18orf21+ctrl' 'SNTG2+ctrl' 'PNMAL2+ctrl' 'CNGA1+ctrl' 'C9orf152+ctrl'
 'SDPR+ctrl' 'TMC5+ctrl' 'C7orf26+ctrl' 'FRMD5+ctrl' 'SLC6A20+ctrl'
 'C21orf59+ctrl' 'TNFRSF25+ctrl' 'LRRC10B+ctrl' 'KCNJ12+ctrl' 'ATP5L+ctrl'
 'CDH23+ctrl' 'ABCA2+ctrl' 'CHRDL2+ctrl' 'ATP5D+ctrl' 'CCR6+ctrl'
 'C15orf52+ctrl' 'PGAP1+ctrl' 'KCNH8+ctrl' 'C1orf21+ctrl' 'CCDC166+ctrl'
 'CRISPLD1+ctrl' 'VAT1L+ctrl' 'SMN1+ctrl' 'USMG5+ctrl' 'PARP3+ctrl'
 'SEM1+ctrl' 'GOLGA7B+ctrl' 'LCN6+ctrl' 'TOMM20L+ctrl' 'HASPIN+ctrl'
 'C22orf46+ctrl' 'ST8SIA4+ctrl' 'RAD9B+ctrl' 'MED14OS+ctrl' 'SULT4A1+ctrl'
 'ATG101+ctrl' 'MRPL57+ctrl' 'SPATA7+ctrl' 'ALDH6A1+ctrl' 'PRSS38+ctrl'
 'MS4A12+ctrl' 'ADAMTS15+ctrl' 'COLEC12+ctrl' 'FAM96B+ctrl'
 'C14orf166+ctrl' 'SOCS6+ctrl' 'RGS13+ctrl' 'KLHL26+ctrl' 'KDM4D+ctrl'
 'BAALC+ctrl' 'SPOCK1+ctrl' 'ATP5J2+ctrl' 'OTUD7A+ctrl' 'C8orf59+ctrl'
 'KIAA0556+ctrl' 'MUM1+ctrl' 'TMTC2+ctrl' 'ABCC9+ctrl' 'C16orf59+ctrl'
 'BTBD6+ctrl' 'FAM92B+ctrl' 'TNFRSF13C+ctrl' 'SORCS2+ctrl' 'HABP4+ctrl'
 'PGM5+ctrl' 'CALCR+ctrl' 'NARR+ctrl' 'ADAMTS8+ctrl' 'SCGB1C2+ctrl'
 'CACNG7+ctrl' 'HPSE+ctrl' 'LOC101927322+ctrl' 'TRIM16L+ctrl' 'TKFC+ctrl'
 'CRIP1+ctrl' 'GRAMD2A+ctrl' 'FAXC+ctrl' 'GGT7+ctrl' 'MTERF3+ctrl'
 'IKBKAP+ctrl' 'SLC16A3+ctrl' 'PTGDS+ctrl' 'FAM163A+ctrl' 'MOSPD2+ctrl'
 'RASL10A+ctrl' 'NGB+ctrl' 'KIAA1429+ctrl' 'ABCD1+ctrl' 'GNB1L+ctrl'
 'C17orf64+ctrl' 'ORAOV1+ctrl' 'UBOX5+ctrl' 'BOD1L2+ctrl' 'CLIP4+ctrl'
 'C1orf226+ctrl' 'SERF1A+ctrl' 'RASEF+ctrl' 'LOC389895+ctrl' 'RIMKLA+ctrl'
 'DZANK1+ctrl' 'SPSB4+ctrl' 'SOBP+ctrl' 'WNT7B+ctrl' 'SLX4+ctrl'
 'VSTM5+ctrl' 'CBWD7+ctrl' 'NT5DC4+ctrl']
Local copy of pyg dataset is detected. Loading...
Done!
Creating new splits....
Saving new splits at ./data/wahn_1\splits\wahn_1_simulation_1_0.75.pkl
Simulation split test composition:
combo_seen0:0
combo_seen1:0
combo_seen2:0
unseen_single:272
Done!
Creating dataloaders....
Done!

In [ ]:
from gears import PertData, GEARS
gears_model = GEARS(pert_data, device = 'cuda:0', 
                        weight_bias_track = False, 
                        proj_name = 'gears',
                        exp_name = 'gears')
gears_model.model_initialize(hidden_size = 64)

Found local copy...

In [9]:
gears_model.train(epochs = 20,lr= 1e-3)

Start Training...
Epoch 1 Step 1 Train Loss: 1.0317
Epoch 1 Step 51 Train Loss: 0.5825
Epoch 1 Step 101 Train Loss: 0.9404
Epoch 1 Step 151 Train Loss: 1.1994
Epoch 1 Step 201 Train Loss: 0.9587
Epoch 1 Step 251 Train Loss: 0.8121
Epoch 1 Step 301 Train Loss: 0.7600
Epoch 1 Step 351 Train Loss: 0.8238
Epoch 1 Step 401 Train Loss: 1.2188
Epoch 1 Step 451 Train Loss: 1.1201
Epoch 1 Step 501 Train Loss: 0.9980
Epoch 1 Step 551 Train Loss: 0.9658
Epoch 1 Step 601 Train Loss: 0.9087
Epoch 1 Step 651 Train Loss: 1.4600
Epoch 1 Step 701 Train Loss: 0.7493
Epoch 1 Step 751 Train Loss: 0.7600
Epoch 1 Step 801 Train Loss: 0.8957
Epoch 1 Step 851 Train Loss: 0.9367
Epoch 1: Train Overall MSE: 0.0470 Validation Overall MSE: 0.0421.
Train Top 20 DE MSE: 0.2564 Validation Top 20 DE MSE: 0.2493.
Epoch 2 Step 1 Train Loss: 1.0122
Epoch 2 Step 51 Train Loss: 0.8452
Epoch 2 Step 101 Train Loss: 1.1026
Epoch 2 Step 151 Train Loss: 0.7144
Epoch 2 Step 201 Train Loss: 1.2302
Epoch 2 Step 251 Train Loss: 0.8365
Epoch 2 Step 301 Train Loss: 0.9792
Epoch 2 Step 351 Train Loss: 0.8114
Epoch 2 Step 401 Train Loss: 0.7878
Epoch 2 Step 451 Train Loss: 0.8673
Epoch 2 Step 501 Train Loss: 1.0816
Epoch 2 Step 551 Train Loss: 0.8697
Epoch 2 Step 601 Train Loss: 1.2636
Epoch 2 Step 651 Train Loss: 0.9438
Epoch 2 Step 701 Train Loss: 0.7388
Epoch 2 Step 751 Train Loss: 1.1283
Epoch 2 Step 801 Train Loss: 0.8129
Epoch 2 Step 851 Train Loss: 1.1031
Epoch 2: Train Overall MSE: 0.0394 Validation Overall MSE: 0.0375.
Train Top 20 DE MSE: 0.2476 Validation Top 20 DE MSE: 0.2446.
Epoch 3 Step 1 Train Loss: 1.1379
Epoch 3 Step 51 Train Loss: 0.8062
Epoch 3 Step 101 Train Loss: 0.8329
Epoch 3 Step 151 Train Loss: 1.1155
Epoch 3 Step 201 Train Loss: 0.8108
Epoch 3 Step 251 Train Loss: 0.8871
Epoch 3 Step 301 Train Loss: 0.7790
Epoch 3 Step 351 Train Loss: 0.9715
Epoch 3 Step 401 Train Loss: 0.6741
Epoch 3 Step 451 Train Loss: 0.9893
Epoch 3 Step 501 Train Loss: 0.9001
Epoch 3 Step 551 Train Loss: 0.9411
Epoch 3 Step 601 Train Loss: 0.8750
Epoch 3 Step 651 Train Loss: 0.9374
Epoch 3 Step 701 Train Loss: 0.8018
Epoch 3 Step 751 Train Loss: 0.7287
Epoch 3 Step 801 Train Loss: 0.8461
Epoch 3 Step 851 Train Loss: 0.8151
Epoch 3: Train Overall MSE: 0.0382 Validation Overall MSE: 0.0359.
Train Top 20 DE MSE: 0.2487 Validation Top 20 DE MSE: 0.2429.
Epoch 4 Step 1 Train Loss: 0.8312
Epoch 4 Step 51 Train Loss: 1.0967
Epoch 4 Step 101 Train Loss: 0.8561
Epoch 4 Step 151 Train Loss: 0.6908
Epoch 4 Step 201 Train Loss: 1.3693
Epoch 4 Step 251 Train Loss: 1.0678
Epoch 4 Step 301 Train Loss: 0.6830
Epoch 4 Step 351 Train Loss: 0.8941
Epoch 4 Step 401 Train Loss: 0.6875
Epoch 4 Step 451 Train Loss: 0.6957
Epoch 4 Step 501 Train Loss: 0.9278
Epoch 4 Step 551 Train Loss: 0.7580
Epoch 4 Step 601 Train Loss: 0.9953
Epoch 4 Step 651 Train Loss: 0.5437
Epoch 4 Step 701 Train Loss: 0.7356
Epoch 4 Step 751 Train Loss: 0.8847
Epoch 4 Step 801 Train Loss: 0.8483
Epoch 4 Step 851 Train Loss: 1.0439
Epoch 4: Train Overall MSE: 0.0366 Validation Overall MSE: 0.0351.
Train Top 20 DE MSE: 0.2487 Validation Top 20 DE MSE: 0.2454.
Epoch 5 Step 1 Train Loss: 0.7564
Epoch 5 Step 51 Train Loss: 0.9565
Epoch 5 Step 101 Train Loss: 1.1567
Epoch 5 Step 151 Train Loss: 1.0665
Epoch 5 Step 201 Train Loss: 1.0614
Epoch 5 Step 251 Train Loss: 0.8251
Epoch 5 Step 301 Train Loss: 0.8842
Epoch 5 Step 351 Train Loss: 0.9107
Epoch 5 Step 401 Train Loss: 1.1037
Epoch 5 Step 451 Train Loss: 1.0091
Epoch 5 Step 501 Train Loss: 0.5302
Epoch 5 Step 551 Train Loss: 0.8994
Epoch 5 Step 601 Train Loss: 1.0133
Epoch 5 Step 651 Train Loss: 0.6885
Epoch 5 Step 701 Train Loss: 0.9681
Epoch 5 Step 751 Train Loss: 1.0227
Epoch 5 Step 801 Train Loss: 0.9639
Epoch 5 Step 851 Train Loss: 0.9473
Epoch 5: Train Overall MSE: 0.0365 Validation Overall MSE: 0.0355.
Train Top 20 DE MSE: 0.2462 Validation Top 20 DE MSE: 0.2459.
Epoch 6 Step 1 Train Loss: 0.8887
Epoch 6 Step 51 Train Loss: 0.8940
Epoch 6 Step 101 Train Loss: 0.9422
Epoch 6 Step 151 Train Loss: 0.9667
Epoch 6 Step 201 Train Loss: 0.9583
Epoch 6 Step 251 Train Loss: 0.9415
Epoch 6 Step 301 Train Loss: 0.8975
Epoch 6 Step 351 Train Loss: 0.8380
Epoch 6 Step 401 Train Loss: 0.9320
Epoch 6 Step 451 Train Loss: 0.6294
Epoch 6 Step 501 Train Loss: 1.3067
Epoch 6 Step 551 Train Loss: 0.9986
Epoch 6 Step 601 Train Loss: 0.7752
Epoch 6 Step 651 Train Loss: 1.0020
Epoch 6 Step 701 Train Loss: 0.9120
Epoch 6 Step 751 Train Loss: 0.9859
Epoch 6 Step 801 Train Loss: 0.8012
Epoch 6 Step 851 Train Loss: 0.9318
Epoch 6: Train Overall MSE: 0.0363 Validation Overall MSE: 0.0356.
Train Top 20 DE MSE: 0.2457 Validation Top 20 DE MSE: 0.2465.
Epoch 7 Step 1 Train Loss: 0.9368
Epoch 7 Step 51 Train Loss: 0.8238
Epoch 7 Step 101 Train Loss: 0.7279
Epoch 7 Step 151 Train Loss: 0.8947
Epoch 7 Step 201 Train Loss: 1.1238
Epoch 7 Step 251 Train Loss: 0.6879
Epoch 7 Step 301 Train Loss: 0.8884
Epoch 7 Step 351 Train Loss: 1.0389
Epoch 7 Step 401 Train Loss: 0.5824
Epoch 7 Step 451 Train Loss: 1.0907
Epoch 7 Step 501 Train Loss: 0.8944
Epoch 7 Step 551 Train Loss: 0.8569
Epoch 7 Step 601 Train Loss: 1.1368
Epoch 7 Step 651 Train Loss: 1.1349
Epoch 7 Step 701 Train Loss: 0.8819
Epoch 7 Step 751 Train Loss: 0.8589
Epoch 7 Step 801 Train Loss: 0.7531
Epoch 7 Step 851 Train Loss: 0.6207
Epoch 7: Train Overall MSE: 0.0358 Validation Overall MSE: 0.0353.
Train Top 20 DE MSE: 0.2437 Validation Top 20 DE MSE: 0.2466.
Epoch 8 Step 1 Train Loss: 0.8185
Epoch 8 Step 51 Train Loss: 0.8281
Epoch 8 Step 101 Train Loss: 0.7696
Epoch 8 Step 151 Train Loss: 0.9832
Epoch 8 Step 201 Train Loss: 0.7172
Epoch 8 Step 251 Train Loss: 0.7278
Epoch 8 Step 301 Train Loss: 0.8605
Epoch 8 Step 351 Train Loss: 0.5378
Epoch 8 Step 401 Train Loss: 0.7956
Epoch 8 Step 451 Train Loss: 0.6955
Epoch 8 Step 501 Train Loss: 0.7991
Epoch 8 Step 551 Train Loss: 0.6539
Epoch 8 Step 601 Train Loss: 0.8692
Epoch 8 Step 651 Train Loss: 0.8560
Epoch 8 Step 701 Train Loss: 1.2372
Epoch 8 Step 751 Train Loss: 0.9379
Epoch 8 Step 801 Train Loss: 0.7657
Epoch 8 Step 851 Train Loss: 1.0749
Epoch 8: Train Overall MSE: 0.0353 Validation Overall MSE: 0.0350.
Train Top 20 DE MSE: 0.2437 Validation Top 20 DE MSE: 0.2461.
Epoch 9 Step 1 Train Loss: 0.8484
Epoch 9 Step 51 Train Loss: 0.8884
Epoch 9 Step 101 Train Loss: 0.9015
Epoch 9 Step 151 Train Loss: 0.8539
Epoch 9 Step 201 Train Loss: 1.0504
Epoch 9 Step 251 Train Loss: 0.7863
Epoch 9 Step 301 Train Loss: 1.1269
Epoch 9 Step 351 Train Loss: 1.0116
Epoch 9 Step 401 Train Loss: 0.7701
Epoch 9 Step 451 Train Loss: 1.0745
Epoch 9 Step 501 Train Loss: 0.9401
Epoch 9 Step 551 Train Loss: 1.0543
Epoch 9 Step 601 Train Loss: 0.6689
Epoch 9 Step 651 Train Loss: 1.0609
Epoch 9 Step 701 Train Loss: 1.2254
Epoch 9 Step 751 Train Loss: 1.0223
Epoch 9 Step 801 Train Loss: 0.6552
Epoch 9 Step 851 Train Loss: 0.9329
Epoch 9: Train Overall MSE: 0.0349 Validation Overall MSE: 0.0349.
Train Top 20 DE MSE: 0.2435 Validation Top 20 DE MSE: 0.2456.
Epoch 10 Step 1 Train Loss: 0.6226
Epoch 10 Step 51 Train Loss: 1.0910
Epoch 10 Step 101 Train Loss: 1.0514
Epoch 10 Step 151 Train Loss: 0.9818
Epoch 10 Step 201 Train Loss: 1.0646
Epoch 10 Step 251 Train Loss: 0.9806
Epoch 10 Step 301 Train Loss: 0.9312
Epoch 10 Step 351 Train Loss: 0.9187
Epoch 10 Step 401 Train Loss: 0.9194
Epoch 10 Step 451 Train Loss: 0.7761
Epoch 10 Step 501 Train Loss: 0.5850
Epoch 10 Step 551 Train Loss: 0.8380
Epoch 10 Step 601 Train Loss: 0.8787
Epoch 10 Step 651 Train Loss: 1.1915
Epoch 10 Step 701 Train Loss: 1.1006
Epoch 10 Step 751 Train Loss: 0.6443
Epoch 10 Step 801 Train Loss: 1.0285
Epoch 10 Step 851 Train Loss: 0.9446
Epoch 10: Train Overall MSE: 0.0351 Validation Overall MSE: 0.0351.
Train Top 20 DE MSE: 0.2433 Validation Top 20 DE MSE: 0.2462.
Epoch 11 Step 1 Train Loss: 0.7371
Epoch 11 Step 51 Train Loss: 0.8918
Epoch 11 Step 101 Train Loss: 0.8128
Epoch 11 Step 151 Train Loss: 0.8805
Epoch 11 Step 201 Train Loss: 1.0444
Epoch 11 Step 251 Train Loss: 0.7627
Epoch 11 Step 301 Train Loss: 0.6537
Epoch 11 Step 351 Train Loss: 0.9739
Epoch 11 Step 401 Train Loss: 1.0604
Epoch 11 Step 451 Train Loss: 0.7106
Epoch 11 Step 501 Train Loss: 1.1386
Epoch 11 Step 551 Train Loss: 0.7896
Epoch 11 Step 601 Train Loss: 0.7181
Epoch 11 Step 651 Train Loss: 0.8654
Epoch 11 Step 701 Train Loss: 0.8986
Epoch 11 Step 751 Train Loss: 0.8854
Epoch 11 Step 801 Train Loss: 1.4728
Epoch 11 Step 851 Train Loss: 1.3779
Epoch 11: Train Overall MSE: 0.0356 Validation Overall MSE: 0.0357.
Train Top 20 DE MSE: 0.2437 Validation Top 20 DE MSE: 0.2471.
Epoch 12 Step 1 Train Loss: 0.7604
Epoch 12 Step 51 Train Loss: 0.8795
Epoch 12 Step 101 Train Loss: 0.8010
Epoch 12 Step 151 Train Loss: 0.6666
Epoch 12 Step 201 Train Loss: 0.9619
Epoch 12 Step 251 Train Loss: 0.6959
Epoch 12 Step 301 Train Loss: 0.8786
Epoch 12 Step 351 Train Loss: 0.7430
Epoch 12 Step 401 Train Loss: 0.7945
Epoch 12 Step 451 Train Loss: 0.6505
Epoch 12 Step 501 Train Loss: 0.8038
Epoch 12 Step 551 Train Loss: 0.8748
Epoch 12 Step 601 Train Loss: 0.7709
Epoch 12 Step 651 Train Loss: 0.8893
Epoch 12 Step 701 Train Loss: 0.9361
Epoch 12 Step 751 Train Loss: 0.7577
Epoch 12 Step 801 Train Loss: 1.1871
Epoch 12 Step 851 Train Loss: 0.8653
Epoch 12: Train Overall MSE: 0.0357 Validation Overall MSE: 0.0360.
Train Top 20 DE MSE: 0.2436 Validation Top 20 DE MSE: 0.2473.
Epoch 13 Step 1 Train Loss: 0.9781
Epoch 13 Step 51 Train Loss: 0.7793
Epoch 13 Step 101 Train Loss: 0.7109
Epoch 13 Step 151 Train Loss: 0.8666
Epoch 13 Step 201 Train Loss: 0.9315
Epoch 13 Step 251 Train Loss: 1.0289
Epoch 13 Step 301 Train Loss: 0.9404
Epoch 13 Step 351 Train Loss: 0.9950
Epoch 13 Step 401 Train Loss: 0.9742
Epoch 13 Step 451 Train Loss: 0.9932
Epoch 13 Step 501 Train Loss: 0.8594
Epoch 13 Step 551 Train Loss: 1.5358
Epoch 13 Step 601 Train Loss: 1.0394
Epoch 13 Step 651 Train Loss: 0.8062
Epoch 13 Step 701 Train Loss: 0.9405
Epoch 13 Step 751 Train Loss: 0.5255
Epoch 13 Step 801 Train Loss: 1.0388
Epoch 13 Step 851 Train Loss: 0.8438
Epoch 13: Train Overall MSE: 0.0352 Validation Overall MSE: 0.0349.
Train Top 20 DE MSE: 0.2429 Validation Top 20 DE MSE: 0.2460.
Epoch 14 Step 1 Train Loss: 0.8649
Epoch 14 Step 51 Train Loss: 0.8085
Epoch 14 Step 101 Train Loss: 1.0970
Epoch 14 Step 151 Train Loss: 1.0000
Epoch 14 Step 201 Train Loss: 1.5013
Epoch 14 Step 251 Train Loss: 0.9434
Epoch 14 Step 301 Train Loss: 0.9780
Epoch 14 Step 351 Train Loss: 0.6234
Epoch 14 Step 401 Train Loss: 0.8501
Epoch 14 Step 451 Train Loss: 0.8812
Epoch 14 Step 501 Train Loss: 0.8239
Epoch 14 Step 551 Train Loss: 0.7752
Epoch 14 Step 601 Train Loss: 1.0778
Epoch 14 Step 651 Train Loss: 0.8462
Epoch 14 Step 701 Train Loss: 0.7208
Epoch 14 Step 751 Train Loss: 0.7662
Epoch 14 Step 801 Train Loss: 0.6888
Epoch 14 Step 851 Train Loss: 0.8917
Epoch 14: Train Overall MSE: 0.0356 Validation Overall MSE: 0.0356.
Train Top 20 DE MSE: 0.2433 Validation Top 20 DE MSE: 0.2469.
Epoch 15 Step 1 Train Loss: 0.8924
Epoch 15 Step 51 Train Loss: 1.1644
Epoch 15 Step 101 Train Loss: 1.1105
Epoch 15 Step 151 Train Loss: 1.0226
Epoch 15 Step 201 Train Loss: 0.8454
Epoch 15 Step 251 Train Loss: 0.8182
Epoch 15 Step 301 Train Loss: 0.9147
Epoch 15 Step 351 Train Loss: 0.8470
Epoch 15 Step 401 Train Loss: 0.8827
Epoch 15 Step 451 Train Loss: 0.5747
Epoch 15 Step 501 Train Loss: 1.0053
Epoch 15 Step 551 Train Loss: 0.7510
Epoch 15 Step 601 Train Loss: 0.9395
Epoch 15 Step 651 Train Loss: 0.8932
Epoch 15 Step 701 Train Loss: 0.7178
Epoch 15 Step 751 Train Loss: 1.0822
Epoch 15 Step 801 Train Loss: 0.7017
Epoch 15 Step 851 Train Loss: 1.0015
Epoch 15: Train Overall MSE: 0.0351 Validation Overall MSE: 0.0351.
Train Top 20 DE MSE: 0.2441 Validation Top 20 DE MSE: 0.2459.
Epoch 16 Step 1 Train Loss: 0.6355
Epoch 16 Step 51 Train Loss: 1.0382
Epoch 16 Step 101 Train Loss: 0.7610
Epoch 16 Step 151 Train Loss: 1.0520
Epoch 16 Step 201 Train Loss: 0.8418
Epoch 16 Step 251 Train Loss: 0.7257
Epoch 16 Step 301 Train Loss: 0.8654
Epoch 16 Step 351 Train Loss: 0.7775
Epoch 16 Step 401 Train Loss: 0.8734
Epoch 16 Step 451 Train Loss: 0.9712
Epoch 16 Step 501 Train Loss: 0.8261
Epoch 16 Step 551 Train Loss: 0.8173
Epoch 16 Step 601 Train Loss: 0.7778
Epoch 16 Step 651 Train Loss: 0.6008
Epoch 16 Step 701 Train Loss: 0.8862
Epoch 16 Step 751 Train Loss: 1.1739
Epoch 16 Step 801 Train Loss: 0.6483
Epoch 16 Step 851 Train Loss: 0.7214
Epoch 16: Train Overall MSE: 0.0365 Validation Overall MSE: 0.0361.
Train Top 20 DE MSE: 0.2432 Validation Top 20 DE MSE: 0.2473.
Epoch 17 Step 1 Train Loss: 0.6560
Epoch 17 Step 51 Train Loss: 1.0846
Epoch 17 Step 101 Train Loss: 0.8551
Epoch 17 Step 151 Train Loss: 0.8161
Epoch 17 Step 201 Train Loss: 0.8354
Epoch 17 Step 251 Train Loss: 0.3454
Epoch 17 Step 301 Train Loss: 0.9206
Epoch 17 Step 351 Train Loss: 0.7834
Epoch 17 Step 401 Train Loss: 0.8765
Epoch 17 Step 451 Train Loss: 0.7154
Epoch 17 Step 501 Train Loss: 0.6080
Epoch 17 Step 551 Train Loss: 0.6775
Epoch 17 Step 601 Train Loss: 1.0685
Epoch 17 Step 651 Train Loss: 0.9811
Epoch 17 Step 701 Train Loss: 0.7565
Epoch 17 Step 751 Train Loss: 0.9421
Epoch 17 Step 801 Train Loss: 1.0097
Epoch 17 Step 851 Train Loss: 0.8952
Epoch 17: Train Overall MSE: 0.0352 Validation Overall MSE: 0.0351.
Train Top 20 DE MSE: 0.2437 Validation Top 20 DE MSE: 0.2459.
Epoch 18 Step 1 Train Loss: 0.7818
Epoch 18 Step 51 Train Loss: 0.9149
Epoch 18 Step 101 Train Loss: 0.9341
Epoch 18 Step 151 Train Loss: 0.7074
Epoch 18 Step 201 Train Loss: 0.0057
Epoch 18 Step 251 Train Loss: 0.7735
Epoch 18 Step 301 Train Loss: 0.9242
Epoch 18 Step 351 Train Loss: 0.7532
Epoch 18 Step 401 Train Loss: 0.8992
Epoch 18 Step 451 Train Loss: 0.7454
Epoch 18 Step 501 Train Loss: 0.9450
Epoch 18 Step 551 Train Loss: 0.7684
Epoch 18 Step 601 Train Loss: 0.5802
Epoch 18 Step 651 Train Loss: 0.8679
Epoch 18 Step 701 Train Loss: 1.1999
Epoch 18 Step 751 Train Loss: 0.8386
Epoch 18 Step 801 Train Loss: 0.9929
Epoch 18 Step 851 Train Loss: 0.7813
Epoch 18: Train Overall MSE: 0.0354 Validation Overall MSE: 0.0352.
Train Top 20 DE MSE: 0.2433 Validation Top 20 DE MSE: 0.2463.
Epoch 19 Step 1 Train Loss: 1.0706
Epoch 19 Step 51 Train Loss: 1.0784
Epoch 19 Step 101 Train Loss: 0.9308
Epoch 19 Step 151 Train Loss: 1.2641
Epoch 19 Step 201 Train Loss: 1.2251
Epoch 19 Step 251 Train Loss: 0.8583
Epoch 19 Step 301 Train Loss: 0.9727
Epoch 19 Step 351 Train Loss: 1.0810
Epoch 19 Step 401 Train Loss: 0.7530
Epoch 19 Step 451 Train Loss: 0.8037
Epoch 19 Step 501 Train Loss: 0.8925
Epoch 19 Step 551 Train Loss: 0.8399
Epoch 19 Step 601 Train Loss: 0.7688
Epoch 19 Step 651 Train Loss: 0.9173
Epoch 19 Step 701 Train Loss: 0.8706
Epoch 19 Step 751 Train Loss: 0.8253
Epoch 19 Step 801 Train Loss: 0.9200
Epoch 19 Step 851 Train Loss: 0.8491
Epoch 19: Train Overall MSE: 0.0363 Validation Overall MSE: 0.0356.
Train Top 20 DE MSE: 0.2437 Validation Top 20 DE MSE: 0.2462.
Epoch 20 Step 1 Train Loss: 0.9065
Epoch 20 Step 51 Train Loss: 0.8208
Epoch 20 Step 101 Train Loss: 1.0968
Epoch 20 Step 151 Train Loss: 0.7237
Epoch 20 Step 201 Train Loss: 0.7872
Epoch 20 Step 251 Train Loss: 1.0871
Epoch 20 Step 301 Train Loss: 1.0321
Epoch 20 Step 351 Train Loss: 0.6043
Epoch 20 Step 401 Train Loss: 0.9796
Epoch 20 Step 451 Train Loss: 0.9074
Epoch 20 Step 501 Train Loss: 0.9654
Epoch 20 Step 551 Train Loss: 0.9737
Epoch 20 Step 601 Train Loss: 0.8153
Epoch 20 Step 651 Train Loss: 1.3050
Epoch 20 Step 701 Train Loss: 0.7775
Epoch 20 Step 751 Train Loss: 0.7021
Epoch 20 Step 801 Train Loss: 0.8674
Epoch 20 Step 851 Train Loss: 0.7436
Epoch 20: Train Overall MSE: 0.0355 Validation Overall MSE: 0.0352.
Train Top 20 DE MSE: 0.2432 Validation Top 20 DE MSE: 0.2462.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.2510
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: nan
test_combo_seen0_pearson: nan
test_combo_seen0_mse_de: nan
test_combo_seen0_pearson_de: nan
test_combo_seen1_mse: nan
test_combo_seen1_pearson: nan
test_combo_seen1_mse_de: nan
test_combo_seen1_pearson_de: nan
test_combo_seen2_mse: nan
test_combo_seen2_pearson: nan
test_combo_seen2_mse_de: nan
test_combo_seen2_pearson_de: nan
test_unseen_single_mse: 0.03840274
test_unseen_single_pearson: 0.9426738759129688
test_unseen_single_mse_de: 0.25103393
test_unseen_single_pearson_de: 7.117637835999282e-05
test_combo_seen0_pearson_delta: nan
test_combo_seen0_frac_opposite_direction_top20_non_dropout: nan
test_combo_seen0_frac_sigma_below_1_non_dropout: nan
test_combo_seen0_mse_top20_de_non_dropout: nan
test_combo_seen1_pearson_delta: nan
test_combo_seen1_frac_opposite_direction_top20_non_dropout: nan
test_combo_seen1_frac_sigma_below_1_non_dropout: nan
test_combo_seen1_mse_top20_de_non_dropout: nan
test_combo_seen2_pearson_delta: nan
test_combo_seen2_frac_opposite_direction_top20_non_dropout: nan
test_combo_seen2_frac_sigma_below_1_non_dropout: nan
test_combo_seen2_mse_top20_de_non_dropout: nan
test_unseen_single_pearson_delta: 0.026711492823747216
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.4928308823529412
test_unseen_single_frac_sigma_below_1_non_dropout: 0.15349264705882354
test_unseen_single_mse_top20_de_non_dropout: 0.3458052969505628
Done!

In [3]:
import sys
sys.path.append('../')
from gears import PertData

pert_data = PertData('./data') # specific saved folder
pert_data.load(data_path = './data/wahn_1') # load the processed data, the path is saved folder + dataset_name
pert_data.prepare_split(split = 'simulation', seed = 1) # get data split with seed
pert_data.get_dataloader(batch_size = 32, test_batch_size = 128) # prepare data loader

from gears import PertData, GEARS
gears_model = GEARS(pert_data, device = 'cuda:0', 
                        weight_bias_track = False, 
                        proj_name = 'gears',
                        exp_name = 'gt-gears')
gears_model.model_initialize(hidden_size = 64)
gears_model.train(epochs = 20,lr= 1e-3)

Found local copy...
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['LETM2+ctrl' 'PRR23A+ctrl' 'GOLGA6C+ctrl' 'NLRP3+ctrl' 'CCNYL1+ctrl'
 'TMEM144+ctrl' 'SLITRK5+ctrl' 'ZACN+ctrl' 'CRACR2B+ctrl' 'FAM89A+ctrl'
 'ICE2+ctrl' 'PLD2+ctrl' 'ST8SIA6+ctrl' 'C10orf111+ctrl' 'FANCC+ctrl'
 'GRAMD2+ctrl' 'U2AF1L5+ctrl' 'LRRK1+ctrl' 'WRB+ctrl' 'CELF5+ctrl'
 'NEFL+ctrl' 'CLDN11+ctrl' 'ELOC+ctrl' 'HDGFRP3+ctrl' 'GPR12+ctrl'
 'NTSR2+ctrl' 'SKIV2L2+ctrl' 'PLEK2+ctrl' 'DGCR14+ctrl' 'CX3CL1+ctrl'
 'NUPL2+ctrl' 'GNMT+ctrl' 'KLHL14+ctrl' 'TANC1+ctrl' 'SLC17A7+ctrl'
 'AKAP10+ctrl' 'LARGE2+ctrl' 'MYL2+ctrl' 'NARFL+ctrl' 'SAP25+ctrl'
 'FAM173B+ctrl' 'CCDC121+ctrl' 'RBSN+ctrl' 'TEX14+ctrl' 'TSACC+ctrl'
 'FAM189A1+ctrl' 'CPTP+ctrl' 'CTC1+ctrl' 'OPRK1+ctrl' 'PPL+ctrl'
 'NKAIN1+ctrl' 'ATP5O+ctrl' 'UTP14C+ctrl' 'SLC6A3+ctrl' 'SWAP70+ctrl'
 'CFAP20+ctrl' 'SLC22A5+ctrl' 'TMEM229B+ctrl' 'C19orf71+ctrl' 'GNA12+ctrl'
 'HLA+ctrl' 'SF3B6+ctrl' 'C16orf90+ctrl' 'DNAH17+ctrl' 'CCL21+ctrl'
 'C18orf21+ctrl' 'SNTG2+ctrl' 'PNMAL2+ctrl' 'CNGA1+ctrl' 'C9orf152+ctrl'
 'SDPR+ctrl' 'TMC5+ctrl' 'C7orf26+ctrl' 'FRMD5+ctrl' 'SLC6A20+ctrl'
 'C21orf59+ctrl' 'TNFRSF25+ctrl' 'LRRC10B+ctrl' 'KCNJ12+ctrl' 'ATP5L+ctrl'
 'CDH23+ctrl' 'ABCA2+ctrl' 'CHRDL2+ctrl' 'ATP5D+ctrl' 'CCR6+ctrl'
 'C15orf52+ctrl' 'PGAP1+ctrl' 'KCNH8+ctrl' 'C1orf21+ctrl' 'CCDC166+ctrl'
 'CRISPLD1+ctrl' 'VAT1L+ctrl' 'SMN1+ctrl' 'USMG5+ctrl' 'PARP3+ctrl'
 'SEM1+ctrl' 'GOLGA7B+ctrl' 'LCN6+ctrl' 'TOMM20L+ctrl' 'HASPIN+ctrl'
 'C22orf46+ctrl' 'ST8SIA4+ctrl' 'RAD9B+ctrl' 'MED14OS+ctrl' 'SULT4A1+ctrl'
 'ATG101+ctrl' 'MRPL57+ctrl' 'SPATA7+ctrl' 'ALDH6A1+ctrl' 'PRSS38+ctrl'
 'MS4A12+ctrl' 'ADAMTS15+ctrl' 'COLEC12+ctrl' 'FAM96B+ctrl'
 'C14orf166+ctrl' 'SOCS6+ctrl' 'RGS13+ctrl' 'KLHL26+ctrl' 'KDM4D+ctrl'
 'BAALC+ctrl' 'SPOCK1+ctrl' 'ATP5J2+ctrl' 'OTUD7A+ctrl' 'C8orf59+ctrl'
 'KIAA0556+ctrl' 'MUM1+ctrl' 'TMTC2+ctrl' 'ABCC9+ctrl' 'C16orf59+ctrl'
 'BTBD6+ctrl' 'FAM92B+ctrl' 'TNFRSF13C+ctrl' 'SORCS2+ctrl' 'HABP4+ctrl'
 'PGM5+ctrl' 'CALCR+ctrl' 'NARR+ctrl' 'ADAMTS8+ctrl' 'SCGB1C2+ctrl'
 'CACNG7+ctrl' 'HPSE+ctrl' 'LOC101927322+ctrl' 'TRIM16L+ctrl' 'TKFC+ctrl'
 'CRIP1+ctrl' 'GRAMD2A+ctrl' 'FAXC+ctrl' 'GGT7+ctrl' 'MTERF3+ctrl'
 'IKBKAP+ctrl' 'SLC16A3+ctrl' 'PTGDS+ctrl' 'FAM163A+ctrl' 'MOSPD2+ctrl'
 'RASL10A+ctrl' 'NGB+ctrl' 'KIAA1429+ctrl' 'ABCD1+ctrl' 'GNB1L+ctrl'
 'C17orf64+ctrl' 'ORAOV1+ctrl' 'UBOX5+ctrl' 'BOD1L2+ctrl' 'CLIP4+ctrl'
 'C1orf226+ctrl' 'SERF1A+ctrl' 'RASEF+ctrl' 'LOC389895+ctrl' 'RIMKLA+ctrl'
 'DZANK1+ctrl' 'SPSB4+ctrl' 'SOBP+ctrl' 'WNT7B+ctrl' 'SLX4+ctrl'
 'VSTM5+ctrl' 'CBWD7+ctrl' 'NT5DC4+ctrl']
Local copy of pyg dataset is detected. Loading...
Done!
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:0
combo_seen1:0
combo_seen2:0
unseen_single:272
Done!
Creating dataloaders....
Done!

here1

Found local copy...
Start Training...
Epoch 1 Step 1 Train Loss: 0.9558
Epoch 1 Step 51 Train Loss: 0.8469
Epoch 1 Step 101 Train Loss: 0.9644
Epoch 1 Step 151 Train Loss: 0.8752
Epoch 1 Step 201 Train Loss: 1.0404
Epoch 1 Step 251 Train Loss: 0.4789
Epoch 1 Step 301 Train Loss: 0.7091
Epoch 1 Step 351 Train Loss: 0.8779
Epoch 1 Step 401 Train Loss: 1.2279
Epoch 1 Step 451 Train Loss: 1.1050
Epoch 1 Step 501 Train Loss: 0.7680
Epoch 1 Step 551 Train Loss: 1.0380
Epoch 1 Step 601 Train Loss: 1.0040
Epoch 1 Step 651 Train Loss: 0.8779
Epoch 1 Step 701 Train Loss: 1.1075
Epoch 1 Step 751 Train Loss: 0.9035
Epoch 1 Step 801 Train Loss: 1.1707
Epoch 1 Step 851 Train Loss: 1.0243
Epoch 1: Train Overall MSE: 0.0343 Validation Overall MSE: 0.0328.
Train Top 20 DE MSE: 0.2481 Validation Top 20 DE MSE: 0.2426.
Epoch 2 Step 1 Train Loss: 0.9459
Epoch 2 Step 51 Train Loss: 0.9690
Epoch 2 Step 101 Train Loss: 1.0091
Epoch 2 Step 151 Train Loss: 0.9619
Epoch 2 Step 201 Train Loss: 0.6607
Epoch 2 Step 251 Train Loss: 0.9727
Epoch 2 Step 301 Train Loss: 0.5194
Epoch 2 Step 351 Train Loss: 1.1334
Epoch 2 Step 401 Train Loss: 0.8113
Epoch 2 Step 451 Train Loss: 0.8774
Epoch 2 Step 501 Train Loss: 1.0465
Epoch 2 Step 551 Train Loss: 0.8546
Epoch 2 Step 601 Train Loss: 0.9213
Epoch 2 Step 651 Train Loss: 1.0272
Epoch 2 Step 701 Train Loss: 0.7742
Epoch 2 Step 751 Train Loss: 1.3135
Epoch 2 Step 801 Train Loss: 0.7604
Epoch 2 Step 851 Train Loss: 0.8552
Epoch 2: Train Overall MSE: 0.0346 Validation Overall MSE: 0.0337.
Train Top 20 DE MSE: 0.2484 Validation Top 20 DE MSE: 0.2438.
Epoch 3 Step 1 Train Loss: 0.8732
Epoch 3 Step 51 Train Loss: 0.8557
Epoch 3 Step 101 Train Loss: 1.0851
Epoch 3 Step 151 Train Loss: 0.8520
Epoch 3 Step 201 Train Loss: 1.1247
Epoch 3 Step 251 Train Loss: 1.0132
Epoch 3 Step 301 Train Loss: 0.9282
Epoch 3 Step 351 Train Loss: 0.7772
Epoch 3 Step 401 Train Loss: 0.9609
Epoch 3 Step 451 Train Loss: 0.9153
Epoch 3 Step 501 Train Loss: 0.8195
Epoch 3 Step 551 Train Loss: 0.9102
Epoch 3 Step 601 Train Loss: 1.1731
Epoch 3 Step 651 Train Loss: 1.0405
Epoch 3 Step 701 Train Loss: 0.8581
Epoch 3 Step 751 Train Loss: 0.7791
Epoch 3 Step 801 Train Loss: 0.8954
Epoch 3 Step 851 Train Loss: 0.3250
Epoch 3: Train Overall MSE: 0.0341 Validation Overall MSE: 0.0329.
Train Top 20 DE MSE: 0.2471 Validation Top 20 DE MSE: 0.2427.
Epoch 4 Step 1 Train Loss: 0.9084
Epoch 4 Step 51 Train Loss: 0.9203
Epoch 4 Step 101 Train Loss: 1.1615
Epoch 4 Step 151 Train Loss: 0.8955
Epoch 4 Step 201 Train Loss: 0.8195
Epoch 4 Step 251 Train Loss: 1.2886
Epoch 4 Step 301 Train Loss: 0.8664
Epoch 4 Step 351 Train Loss: 1.0308
Epoch 4 Step 401 Train Loss: 0.9310
Epoch 4 Step 451 Train Loss: 0.9627
Epoch 4 Step 501 Train Loss: 0.7430
Epoch 4 Step 551 Train Loss: 0.9724
Epoch 4 Step 601 Train Loss: 1.0733
Epoch 4 Step 651 Train Loss: 0.8995
Epoch 4 Step 701 Train Loss: 1.1194
Epoch 4 Step 751 Train Loss: 1.1390
Epoch 4 Step 801 Train Loss: 0.9354
Epoch 4 Step 851 Train Loss: 0.8000
Epoch 4: Train Overall MSE: 0.0344 Validation Overall MSE: 0.0331.
Train Top 20 DE MSE: 0.2486 Validation Top 20 DE MSE: 0.2449.
Epoch 5 Step 1 Train Loss: 0.8979
Epoch 5 Step 51 Train Loss: 0.9531
Epoch 5 Step 101 Train Loss: 0.6463
Epoch 5 Step 151 Train Loss: 0.7531
Epoch 5 Step 201 Train Loss: 1.1009
Epoch 5 Step 251 Train Loss: 0.9389
Epoch 5 Step 301 Train Loss: 0.7724
Epoch 5 Step 351 Train Loss: 0.9042
Epoch 5 Step 401 Train Loss: 0.6057
Epoch 5 Step 451 Train Loss: 1.0906
Epoch 5 Step 501 Train Loss: 0.9229
Epoch 5 Step 551 Train Loss: 0.8905
Epoch 5 Step 601 Train Loss: 0.9780
Epoch 5 Step 651 Train Loss: 1.2565
Epoch 5 Step 701 Train Loss: 0.6564
Epoch 5 Step 751 Train Loss: 0.7165
Epoch 5 Step 801 Train Loss: 0.8959
Epoch 5 Step 851 Train Loss: 0.5500
Epoch 5: Train Overall MSE: 0.0343 Validation Overall MSE: 0.0331.
Train Top 20 DE MSE: 0.2489 Validation Top 20 DE MSE: 0.2448.
Epoch 6 Step 1 Train Loss: 0.8678
Epoch 6 Step 51 Train Loss: 0.8759
Epoch 6 Step 101 Train Loss: 0.9731
Epoch 6 Step 151 Train Loss: 0.8102
Epoch 6 Step 201 Train Loss: 0.9619
Epoch 6 Step 251 Train Loss: 0.9728
Epoch 6 Step 301 Train Loss: 0.8649
Epoch 6 Step 351 Train Loss: 0.9724
Epoch 6 Step 401 Train Loss: 0.9393
Epoch 6 Step 451 Train Loss: 1.2241
Epoch 6 Step 501 Train Loss: 1.0818
Epoch 6 Step 551 Train Loss: 1.2558
Epoch 6 Step 601 Train Loss: 0.8460
Epoch 6 Step 651 Train Loss: 0.8199
Epoch 6 Step 701 Train Loss: 0.9510
Epoch 6 Step 751 Train Loss: 0.7557
Epoch 6 Step 801 Train Loss: 0.8113
Epoch 6 Step 851 Train Loss: 0.7452
Epoch 6: Train Overall MSE: 0.0345 Validation Overall MSE: 0.0333.
Train Top 20 DE MSE: 0.2495 Validation Top 20 DE MSE: 0.2458.
Epoch 7 Step 1 Train Loss: 1.0427
Epoch 7 Step 51 Train Loss: 0.6494
Epoch 7 Step 101 Train Loss: 1.0615
Epoch 7 Step 151 Train Loss: 0.9813
Epoch 7 Step 201 Train Loss: 0.9464
Epoch 7 Step 251 Train Loss: 0.8043
Epoch 7 Step 301 Train Loss: 0.4375
Epoch 7 Step 351 Train Loss: 0.7334
Epoch 7 Step 401 Train Loss: 0.6667
Epoch 7 Step 451 Train Loss: 0.4754
Epoch 7 Step 501 Train Loss: 1.0933
Epoch 7 Step 551 Train Loss: 1.2116
Epoch 7 Step 601 Train Loss: 0.9681
Epoch 7 Step 651 Train Loss: 1.0348
Epoch 7 Step 701 Train Loss: 0.7043
Epoch 7 Step 751 Train Loss: 1.0118
Epoch 7 Step 801 Train Loss: 1.0014
Epoch 7 Step 851 Train Loss: 1.4426
Epoch 7: Train Overall MSE: 0.0345 Validation Overall MSE: 0.0333.
Train Top 20 DE MSE: 0.2496 Validation Top 20 DE MSE: 0.2459.
Epoch 8 Step 1 Train Loss: 1.1637
Epoch 8 Step 51 Train Loss: 0.9263
Epoch 8 Step 101 Train Loss: 1.3035
Epoch 8 Step 151 Train Loss: 1.0906
Epoch 8 Step 201 Train Loss: 0.6436
Epoch 8 Step 251 Train Loss: 0.6335
Epoch 8 Step 301 Train Loss: 0.9031
Epoch 8 Step 351 Train Loss: 0.9762
Epoch 8 Step 401 Train Loss: 0.8998
Epoch 8 Step 451 Train Loss: 1.1896
Epoch 8 Step 501 Train Loss: 1.0782
Epoch 8 Step 551 Train Loss: 1.1586
Epoch 8 Step 601 Train Loss: 0.9744
Epoch 8 Step 651 Train Loss: 1.4621
Epoch 8 Step 701 Train Loss: 0.7885
Epoch 8 Step 751 Train Loss: 1.1465
Epoch 8 Step 801 Train Loss: 0.9983
Epoch 8 Step 851 Train Loss: 1.1565
Epoch 8: Train Overall MSE: 0.0347 Validation Overall MSE: 0.0335.
Train Top 20 DE MSE: 0.2496 Validation Top 20 DE MSE: 0.2460.
Epoch 9 Step 1 Train Loss: 0.9031
Epoch 9 Step 51 Train Loss: 0.9012
Epoch 9 Step 101 Train Loss: 0.8894
Epoch 9 Step 151 Train Loss: 0.7235
Epoch 9 Step 201 Train Loss: 1.0936
Epoch 9 Step 251 Train Loss: 0.7230
Epoch 9 Step 301 Train Loss: 0.7910
Epoch 9 Step 351 Train Loss: 0.7520
Epoch 9 Step 401 Train Loss: 0.9539
Epoch 9 Step 451 Train Loss: 1.0022
Epoch 9 Step 501 Train Loss: 0.8192
Epoch 9 Step 551 Train Loss: 0.9441
Epoch 9 Step 601 Train Loss: 0.9689
Epoch 9 Step 651 Train Loss: 0.6647
Epoch 9 Step 701 Train Loss: 0.9062
Epoch 9 Step 751 Train Loss: 0.8858
Epoch 9 Step 801 Train Loss: 1.0941
Epoch 9 Step 851 Train Loss: 0.8465
Epoch 9: Train Overall MSE: 0.0347 Validation Overall MSE: 0.0336.
Train Top 20 DE MSE: 0.2498 Validation Top 20 DE MSE: 0.2464.
Epoch 10 Step 1 Train Loss: 0.8566
Epoch 10 Step 51 Train Loss: 0.9037
Epoch 10 Step 101 Train Loss: 1.0228
Epoch 10 Step 151 Train Loss: 1.2156
Epoch 10 Step 201 Train Loss: 1.0199
Epoch 10 Step 251 Train Loss: 0.9869
Epoch 10 Step 301 Train Loss: 0.8564
Epoch 10 Step 351 Train Loss: 0.9689
Epoch 10 Step 401 Train Loss: 0.9226
Epoch 10 Step 451 Train Loss: 1.0262
Epoch 10 Step 501 Train Loss: 1.0159
Epoch 10 Step 551 Train Loss: 1.3441
Epoch 10 Step 601 Train Loss: 1.2187
Epoch 10 Step 651 Train Loss: 0.9147
Epoch 10 Step 701 Train Loss: 0.8154
Epoch 10 Step 751 Train Loss: 0.9585
Epoch 10 Step 801 Train Loss: 0.7431
Epoch 10 Step 851 Train Loss: 1.3798
Epoch 10: Train Overall MSE: 0.0346 Validation Overall MSE: 0.0334.
Train Top 20 DE MSE: 0.2494 Validation Top 20 DE MSE: 0.2457.
Epoch 11 Step 1 Train Loss: 1.0454
Epoch 11 Step 51 Train Loss: 0.9445
Epoch 11 Step 101 Train Loss: 1.1808
Epoch 11 Step 151 Train Loss: 1.0146
Epoch 11 Step 201 Train Loss: 0.6852
Epoch 11 Step 251 Train Loss: 0.8773
Epoch 11 Step 301 Train Loss: 1.0831
Epoch 11 Step 351 Train Loss: 0.8456
Epoch 11 Step 401 Train Loss: 0.7582
Epoch 11 Step 451 Train Loss: 0.8131
Epoch 11 Step 501 Train Loss: 1.1574
Epoch 11 Step 551 Train Loss: 1.1404
Epoch 11 Step 601 Train Loss: 1.0831
Epoch 11 Step 651 Train Loss: 0.9090
Epoch 11 Step 701 Train Loss: 0.8435
Epoch 11 Step 751 Train Loss: 0.9368
Epoch 11 Step 801 Train Loss: 0.9601
Epoch 11 Step 851 Train Loss: 0.8329
Epoch 11: Train Overall MSE: 0.0347 Validation Overall MSE: 0.0334.
Train Top 20 DE MSE: 0.2498 Validation Top 20 DE MSE: 0.2458.
Epoch 12 Step 1 Train Loss: 1.0368
Epoch 12 Step 51 Train Loss: 1.1929
Epoch 12 Step 101 Train Loss: 0.8757
Epoch 12 Step 151 Train Loss: 0.7585
Epoch 12 Step 201 Train Loss: 0.6446
Epoch 12 Step 251 Train Loss: 0.9736
Epoch 12 Step 301 Train Loss: 1.0276
Epoch 12 Step 351 Train Loss: 1.1057
Epoch 12 Step 401 Train Loss: 0.9444
Epoch 12 Step 451 Train Loss: 0.9519
Epoch 12 Step 501 Train Loss: 0.9066
Epoch 12 Step 551 Train Loss: 0.9208
Epoch 12 Step 601 Train Loss: 0.8494
Epoch 12 Step 651 Train Loss: 0.8328
Epoch 12 Step 701 Train Loss: 0.7111
Epoch 12 Step 751 Train Loss: 1.0482
Epoch 12 Step 801 Train Loss: 0.7008
Epoch 12 Step 851 Train Loss: 0.8331
Epoch 12: Train Overall MSE: 0.0346 Validation Overall MSE: 0.0334.
Train Top 20 DE MSE: 0.2494 Validation Top 20 DE MSE: 0.2456.
Epoch 13 Step 1 Train Loss: 0.8101
Epoch 13 Step 51 Train Loss: 0.9794
Epoch 13 Step 101 Train Loss: 0.9392
Epoch 13 Step 151 Train Loss: 0.9412
Epoch 13 Step 201 Train Loss: 0.9517
Epoch 13 Step 251 Train Loss: 1.3212
Epoch 13 Step 301 Train Loss: 0.6650
Epoch 13 Step 351 Train Loss: 1.0573
Epoch 13 Step 401 Train Loss: 0.8526
Epoch 13 Step 451 Train Loss: 0.7261
Epoch 13 Step 501 Train Loss: 0.7631
Epoch 13 Step 551 Train Loss: 0.7306
Epoch 13 Step 601 Train Loss: 0.8669
Epoch 13 Step 651 Train Loss: 1.2333
Epoch 13 Step 701 Train Loss: 0.8563
Epoch 13 Step 751 Train Loss: 0.8476
Epoch 13 Step 801 Train Loss: 0.7627
Epoch 13 Step 851 Train Loss: 0.7140
Epoch 13: Train Overall MSE: 0.0347 Validation Overall MSE: 0.0334.
Train Top 20 DE MSE: 0.2495 Validation Top 20 DE MSE: 0.2458.
Epoch 14 Step 1 Train Loss: 1.1319
Epoch 14 Step 51 Train Loss: 1.1648
Epoch 14 Step 101 Train Loss: 0.7982
Epoch 14 Step 151 Train Loss: 0.8422
Epoch 14 Step 201 Train Loss: 0.8110
Epoch 14 Step 251 Train Loss: 1.5963
Epoch 14 Step 301 Train Loss: 1.2035
Epoch 14 Step 351 Train Loss: 0.7130
Epoch 14 Step 401 Train Loss: 0.8551
Epoch 14 Step 451 Train Loss: 0.9612
Epoch 14 Step 501 Train Loss: 0.9412
Epoch 14 Step 551 Train Loss: 0.8309
Epoch 14 Step 601 Train Loss: 0.8170
Epoch 14 Step 651 Train Loss: 1.1329
Epoch 14 Step 701 Train Loss: 0.7693
Epoch 14 Step 751 Train Loss: 1.0926
Epoch 14 Step 801 Train Loss: 1.0624
Epoch 14 Step 851 Train Loss: 0.7478
Epoch 14: Train Overall MSE: 0.0346 Validation Overall MSE: 0.0334.
Train Top 20 DE MSE: 0.2495 Validation Top 20 DE MSE: 0.2457.
Epoch 15 Step 1 Train Loss: 0.9808
Epoch 15 Step 51 Train Loss: 0.8222
Epoch 15 Step 101 Train Loss: 0.8469
Epoch 15 Step 151 Train Loss: 1.1514
Epoch 15 Step 201 Train Loss: 1.0121
Epoch 15 Step 251 Train Loss: 0.7834
Epoch 15 Step 301 Train Loss: 1.1174
Epoch 15 Step 351 Train Loss: 0.7171
Epoch 15 Step 401 Train Loss: 1.1265
Epoch 15 Step 451 Train Loss: 1.2188
Epoch 15 Step 501 Train Loss: 0.9307
Epoch 15 Step 551 Train Loss: 0.9267
Epoch 15 Step 601 Train Loss: 0.6659
Epoch 15 Step 651 Train Loss: 0.9091
Epoch 15 Step 701 Train Loss: 0.6461
Epoch 15 Step 751 Train Loss: 0.8026
Epoch 15 Step 801 Train Loss: 0.7616
Epoch 15 Step 851 Train Loss: 0.7596
Epoch 15: Train Overall MSE: 0.0346 Validation Overall MSE: 0.0334.
Train Top 20 DE MSE: 0.2495 Validation Top 20 DE MSE: 0.2455.
Epoch 16 Step 1 Train Loss: 1.1874
Epoch 16 Step 51 Train Loss: 0.8584
Epoch 16 Step 101 Train Loss: 1.1050
Epoch 16 Step 151 Train Loss: 0.8190
Epoch 16 Step 201 Train Loss: 0.9160
Epoch 16 Step 251 Train Loss: 0.8304
Epoch 16 Step 301 Train Loss: 0.9708
Epoch 16 Step 351 Train Loss: 1.0940
Epoch 16 Step 401 Train Loss: 1.0652
Epoch 16 Step 451 Train Loss: 0.7048
Epoch 16 Step 501 Train Loss: 0.7040
Epoch 16 Step 551 Train Loss: 0.8071
Epoch 16 Step 601 Train Loss: 0.7808
Epoch 16 Step 651 Train Loss: 0.9921
Epoch 16 Step 701 Train Loss: 0.8886
Epoch 16 Step 751 Train Loss: 1.1713
Epoch 16 Step 801 Train Loss: 0.7920
Epoch 16 Step 851 Train Loss: 1.1044
Epoch 16: Train Overall MSE: 0.0347 Validation Overall MSE: 0.0335.
Train Top 20 DE MSE: 0.2495 Validation Top 20 DE MSE: 0.2458.
Epoch 17 Step 1 Train Loss: 0.7017
Epoch 17 Step 51 Train Loss: 0.8720
Epoch 17 Step 101 Train Loss: 0.9330
Epoch 17 Step 151 Train Loss: 0.9368
Epoch 17 Step 201 Train Loss: 1.0358
Epoch 17 Step 251 Train Loss: 1.2250
Epoch 17 Step 301 Train Loss: 0.7692
Epoch 17 Step 351 Train Loss: 1.0824
Epoch 17 Step 401 Train Loss: 0.7506
Epoch 17 Step 451 Train Loss: 0.8388
Epoch 17 Step 501 Train Loss: 0.8000
Epoch 17 Step 551 Train Loss: 0.7682
Epoch 17 Step 601 Train Loss: 0.8034
Epoch 17 Step 651 Train Loss: 0.7660
Epoch 17 Step 701 Train Loss: 0.9941
Epoch 17 Step 751 Train Loss: 0.9761
Epoch 17 Step 801 Train Loss: 0.9272
Epoch 17 Step 851 Train Loss: 1.1884
Epoch 17: Train Overall MSE: 0.0346 Validation Overall MSE: 0.0335.
Train Top 20 DE MSE: 0.2495 Validation Top 20 DE MSE: 0.2457.
Epoch 18 Step 1 Train Loss: 0.9905
Epoch 18 Step 51 Train Loss: 0.7373
Epoch 18 Step 101 Train Loss: 0.6565
Epoch 18 Step 151 Train Loss: 0.8997
Epoch 18 Step 201 Train Loss: 0.9278
Epoch 18 Step 251 Train Loss: 0.8529
Epoch 18 Step 301 Train Loss: 0.9453
Epoch 18 Step 351 Train Loss: 0.9061
Epoch 18 Step 401 Train Loss: 1.1268
Epoch 18 Step 451 Train Loss: 0.7125
Epoch 18 Step 501 Train Loss: 0.7138
Epoch 18 Step 551 Train Loss: 0.7770
Epoch 18 Step 601 Train Loss: 1.1765
Epoch 18 Step 651 Train Loss: 0.9765
Epoch 18 Step 701 Train Loss: 0.9074
Epoch 18 Step 751 Train Loss: 1.0176
Epoch 18 Step 801 Train Loss: 0.8386
Epoch 18 Step 851 Train Loss: 0.9111
Epoch 18: Train Overall MSE: 0.0347 Validation Overall MSE: 0.0335.
Train Top 20 DE MSE: 0.2499 Validation Top 20 DE MSE: 0.2460.
Epoch 19 Step 1 Train Loss: 0.9763
Epoch 19 Step 51 Train Loss: 0.9853
Epoch 19 Step 101 Train Loss: 0.9019
Epoch 19 Step 151 Train Loss: 0.8962
Epoch 19 Step 201 Train Loss: 1.2751
Epoch 19 Step 251 Train Loss: 0.4033
Epoch 19 Step 301 Train Loss: 0.7469
Epoch 19 Step 351 Train Loss: 0.7358
Epoch 19 Step 401 Train Loss: 1.1420
Epoch 19 Step 451 Train Loss: 0.9723
Epoch 19 Step 501 Train Loss: 1.2763
Epoch 19 Step 551 Train Loss: 0.7764
Epoch 19 Step 601 Train Loss: 1.0955
Epoch 19 Step 651 Train Loss: 1.1606
Epoch 19 Step 701 Train Loss: 0.7118
Epoch 19 Step 751 Train Loss: 1.0066
Epoch 19 Step 801 Train Loss: 0.9762
Epoch 19 Step 851 Train Loss: 0.7215
Epoch 19: Train Overall MSE: 0.0347 Validation Overall MSE: 0.0336.
Train Top 20 DE MSE: 0.2503 Validation Top 20 DE MSE: 0.2460.
Epoch 20 Step 1 Train Loss: 0.7255
Epoch 20 Step 51 Train Loss: 0.8075
Epoch 20 Step 101 Train Loss: 1.1986
Epoch 20 Step 151 Train Loss: 1.1055
Epoch 20 Step 201 Train Loss: 1.0810
Epoch 20 Step 251 Train Loss: 0.7790
Epoch 20 Step 301 Train Loss: 0.7758
Epoch 20 Step 351 Train Loss: 1.0217
Epoch 20 Step 401 Train Loss: 0.9666
Epoch 20 Step 451 Train Loss: 1.0173
Epoch 20 Step 501 Train Loss: 0.8234
Epoch 20 Step 551 Train Loss: 0.8387
Epoch 20 Step 601 Train Loss: 1.0718
Epoch 20 Step 651 Train Loss: 0.9356
Epoch 20 Step 701 Train Loss: 0.6590
Epoch 20 Step 751 Train Loss: 0.7347
Epoch 20 Step 801 Train Loss: 1.1800
Epoch 20 Step 851 Train Loss: 0.7418
Epoch 20: Train Overall MSE: 0.0346 Validation Overall MSE: 0.0335.
Train Top 20 DE MSE: 0.2495 Validation Top 20 DE MSE: 0.2458.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.2509
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: nan
test_combo_seen0_pearson: nan
test_combo_seen0_mse_de: nan
test_combo_seen0_pearson_de: nan
test_combo_seen1_mse: nan
test_combo_seen1_pearson: nan
test_combo_seen1_mse_de: nan
test_combo_seen1_pearson_de: nan
test_combo_seen2_mse: nan
test_combo_seen2_pearson: nan
test_combo_seen2_mse_de: nan
test_combo_seen2_pearson_de: nan
test_unseen_single_mse: 0.03558508
test_unseen_single_pearson: 0.9460144380595227
test_unseen_single_mse_de: 0.25093237
test_unseen_single_pearson_de: -0.00011543369108876743
test_combo_seen0_pearson_delta: nan
test_combo_seen0_frac_opposite_direction_top20_non_dropout: nan
test_combo_seen0_frac_sigma_below_1_non_dropout: nan
test_combo_seen0_mse_top20_de_non_dropout: nan
test_combo_seen1_pearson_delta: nan
test_combo_seen1_frac_opposite_direction_top20_non_dropout: nan
test_combo_seen1_frac_sigma_below_1_non_dropout: nan
test_combo_seen1_mse_top20_de_non_dropout: nan
test_combo_seen2_pearson_delta: nan
test_combo_seen2_frac_opposite_direction_top20_non_dropout: nan
test_combo_seen2_frac_sigma_below_1_non_dropout: nan
test_combo_seen2_mse_top20_de_non_dropout: nan
test_unseen_single_pearson_delta: 0.022690048775352443
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.4931985294117646
test_unseen_single_frac_sigma_below_1_non_dropout: 0.15386029411764707
test_unseen_single_mse_top20_de_non_dropout: 0.34742391581942494
Done!